### ISSUE TITLE
Intent filter is not parsed properly

### ISSUE THREAD

**Issue by rongjc** [jaredrummler/APKParser#7]
Try to compare the xml and intent filter of Chrome and youtube. Then intent filter information is not properly captured. Cheers

**Comment by rongjc** [comment]
Tried to push my fix but it seems that I have no permission :(. 
Here is the fix
Model/AndroidManifest.Java
Instead of 
              case "activity":
                activities.add(getAndroidComponent(child, TYPE_ACTIVITY));
                break;
Use
       case "activity":
        case "activity-alias":
                activities.add(getAndroidComponent(child, TYPE_ACTIVITY));
                break;
Some how activity alias is also used. Other than this, There are two more fields for data, pathPattern and path. Please find the link here. https://developer.android.com/guide/topics/manifest/data-element.html

**Comment by jaredrummler** [comment]
You can fork the repo and then submit a pull request. https://help.github.com/articles/using-pull-requests/
